### ISSUE TITLE
function err on wolk about code

### ISSUE THREAD

**Issue by utopiaproject2019** [Wolkabout/WolkConnect-Arduino#25]
Arduino: 1.8.9 (Windows 10), Board: "Arduino/Genuino MKR1000"

C:\Users\jj\AppData\Local\Temp\arduino_modified_sketch_75212\Utopia_Project_2019.ino: In function 'void setup()':

Utopia_Project_2019:197:26: error: too many arguments to function 'WOLK_ERR_T wolk_process(wolk_ctx_t*)'

     wolk_process(&wolk, 5);

                          ^

In file included from C:\Users\jj\AppData\Local\Temp\arduino_modified_sketch_75212\Utopia_Project_2019.ino:10:0:

C:\Program Files (x86)\Arduino\libraries\WolkConnect-3.1.3\src/WolkConn.h:237:12: note: declared here

 WOLK_ERR_T wolk_process (wolk_ctx_t *ctx);

            ^

exit status 1
too many arguments to function 'WOLK_ERR_T wolk_process(wolk_ctx_t*)'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by utopiaproject2019** [comment]
Can you help please??

**Comment by LazarBozic94** [comment]
In our latest update this function was rewritten to receive only wolk_ctx_t* (previous implementation had a bug), but we missed updating the readme files.
If you go into any of the examples you'll see the function call `wolk_process(&wolk)`.
We're sorry for this inconvenience this has caused.
We've since updated the readme files to depict the current version of the library. Thank you for your feedback, it really means a lot to us!
